name: Deploy Wisdom Island
on:
  push:
    branches: [master]  # 触发分支，按需修改
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # 按项目需求指定版本

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: 创建 .env 文件
        run: |
          touch .env
          echo NEXT_PUBLIC_DIFY_API_URL=${{ secrets.NEXT_PUBLIC_DIFY_API_URL }} >> .env
          echo NEXT_PUBLIC_DIFY_API_KEY=${{ secrets.NEXT_PUBLIC_DIFY_API_KEY }} >> .env
          echo NEXT_PUBLIC_DIFY_API_KEY_QUIZ=${{ secrets.NEXT_PUBLIC_DIFY_API_KEY_QUIZ }} >> .env
          echo NEXT_PUBLIC_APP_ID=${{ secrets.NEXT_PUBLIC_APP_ID }} >> .env
          echo NEXT_PUBLIC_WECHAT_APP_ID=${{ secrets.NEXT_PUBLIC_WECHAT_APP_ID }} >> .env
          echo WECHAT_APP_SECRET=${{ secrets.WECHAT_APP_SECRET }} >> .env
          echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env


      - name: Build project
        run: npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip .next package.json package-lock.json public next.config.js .env prisma
        
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "release.zip"
          target: "/root/wisdom-island"
          
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/wisdom-island
            rm -rf .next
            unzip -o release.zip
            npm install --production
            pm2 restart wisdom-island || pm2 start npm --name "wisdom-island" -- start
